### ISSUE TITLE
Migration adding unsupported data type

### ISSUE THREAD

**Issue by awohletz** [jpruetting/refinerycms-image-slideshows#2]
The migration add_image_and_caption_to_image_slides tries to add a column "image" of type "image". My PG database doesn't know what to do with that:

PG::Error: ERROR:  type "image" does not exist
LINE 1: ALTER TABLE "refinery_image_slides" ADD COLUMN "image" image

**Comment by jpruetting** [comment]
This was fixed in a previous commit: https://github.com/jpruetting/refinerycms-image-slideshows/commit/1c61f8f2079e8d61cf6cda5fe3b09c5e7e1a9e04

Make sure you're using the latest version.

``` ruby
gem "refinerycms-image_slideshows", "~> 2.0.2"
```
